//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LSMonitor.rc
//
#define IDCANCEL2                       3
#define ID_BTN_ANNOUNCE                 3
#define IDD_LSMONITOR_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_ANNOUNCE                    129
#define IDD_SMS                         130
#define IDD_CLIENT_VERSION              131
#define IDD_CONTROL                     132
#define IDR_MENU                        133
#define IDD_DIALOG1                     134
#define IDD_SERVER_INFO                 134
#define IDD_NAGLE_REFCOUNT_DIALOG       135
#define IDD_DIALOG_LoginPanel           136
#define IDD_DIALOG2                     137
#define IDD_DIALOG_MONITOR              137
#define IDD_DIALOG_PANEL                138
#define IDC_TAB1                        1002
#define IDC_TAB_ZONE                    1002
#define IDC_LIST_SERVERINFO             1003
#define IDC_LIST4                       1004
#define IDC_LIST_SYSTEMINFO             1004
#define IDC_EDIT_ANNOUNCE               1005
#define IDC_EDIT_USER_ID                1006
#define IDC_CHECK_DIS                   1007
#define IDC_EDIT3                       1008
#define IDC_EDIT_PASSWORD               1008
#define IDSend                          1009
#define IDC_COMBO1                      1010
#define IDC_COMBO_SERVER                1010
#define IDC_CUSTOMSTOP                  1011
#define IDC_EDIT_CUSTOM_STOP            1012
#define IDSTART                         1013
#define IDSTOP1H                        1014
#define ID_BTN_SERVER_SMS               1015
#define ID_BTN_SYSTEM_SMS               1016
#define IDC_STATIC_STRING               1017
#define IDC_EDIT_VERSION                1018
#define IDC_CHECK_USE                   1020
#define ID_SEND                         1021
#define ID_BTN_VERSION                  1022
#define IDC_BUTTON_SEND_COPY            1025
#define IDC_BUTTON_SEND_LOAD            1026
#define ID_BTN_CONTROL                  1030
#define IDC_BUTTON_SEND_INFO            1031
#define IDC_EDIT_IP                     1032
#define IDC_LIST_INFO                   1034
#define IDC_EDIT_CHANGE                 1035
#define ID_BTN_CONNECT_LOG              1036
#define IDC_EDIT                        1037
#define IDC_EDIT_NAGLECOUNT             1038
#define IDC_PROGRESS1                   1039
#define IDC_BUTTON_APPLY                1040
#define IDC_CHECK_SERVERIP              1041
#define IDC_CHECK_SERVERBLOCK           1042
#define IDC_CHECK2                      1042
#define IDC_CHECK_CHANGE                1042
#define IDC_EDIT_MAXUSER                1043
#define IDC_STATIC_SVRINFO              1044
#define IDC_STATIC_MAXUSER              1047
#define ID_SERVERINFO_REQUEST           32772
#define ID_INFO_SERVERINFOREQ           32773
#define ID_SERVERINFOREQ_REQUEST        32774
#define ID_GAMESERVER_SERVERINFOREQ     32775
#define ID_MAINSERVER_MAINSERVEREXIT    32776
#define ID_MAINSERVER_INFODRAW          32777
#define ID_GAMESERVER_INFODRAW          32778
#define ID_MAINSERVER_QUICKALLEXIT      32779
#define ID_MAINSERVER_SAFETYALLEXIT     32780
#define ID_MAINSERVER_RELOADCLOSEINFO   32781
#define ID_MAINSERVER_DBAGENTEXTEND     32782
#define ID_MAINSERVER_GAMESERVEROPTION  32783
#define ID_MAINSERVER_GSRELOADINI       32784
#define ID_MAINSERVER_EXTRAITEMINI      32785
#define ID_MAINSERVER_EVENTSHOPINI      32786
#define ID_GAMESERVER_GAMESERVERVI      32787
#define ID_GAMESERVER_REHACKCONSTANT    32788
#define ID_GAMESERVER_RELOADUSERDISPERSION 32789
#define ID_GAMESERVER_RELOADPROCESSINI  32790
#define ID_GAMESERVER_RELOADINICLASS    32791
#define ID_GAMESERVER_RELOADINIDECO     32792
#define ID_GAMESERVER_RELOADINIETC      32793
#define ID_GAMESERVER_RELOADINIEVENT    32794
#define ID_GAMESERVER_RELOADQUESTINI    32795
#define ID_GAMESERVER_RELOADMODEINI     32796
#define ID_GAMESERVER_RELOADPRESENTINI  32797
#define ID_GAMESERVER_RELOADFISHINGINI  32798
#define ID_GAMESERVER_RELOADEXCA        32799
#define ID_GAMESERVER_RELOADITEMCOMPOUNDINI 32800
#define ID_GAMESERVER_RELOADEXTRAITEMINI 32801
#define ID_GAMESERVER_RELOADTRADEINI    32802
#define ID_GAMESERVER_RELOADLEVELMATCHINI 32803
#define ID_GAMESERVER_RELOADITEMINITCONTROL 32804
#define ID_GAMESERVER_RELOADCONFIGINI   32805
#define ID_GAMESERVER_QUICKEXIT         32806
#define ID_GAMESERVER_SAFETYEXIT        32807
#define ID_GAMESERVER_RELOADHACKCONSTANT 32808
#define ID_MAINSERVER_GSSETNAGLEREFCOUNT 32809
#define ID_MAINSERVER_GSSETNAGLETIME    32810
#define ID_MAINSERVER_LOGINSERVERINFODRAW 32811
#define ID_LOGINSERVER_LOGINSERVERIN    32811
#define ID_Menu                         32812
#define ID_LOGINSERVER_LOGINSERVERIN_FILL 32812
#define ID_MAINSERVER_LOGINSERVERINFODRAW32813 32813
#define ID_MAINSERVER_LOGINSERVERINFODRAW32814 32814
#define ID_LOGINSERVER_INFODRAW         32815
#define ID_LOGINSERVER_LOGINSERVERINFODRAW 32816
#define ID_LSSERVERINFO_ALLBLOCKO       32818
#define ID_LSSERVERINFO_ALLBLOCKOFF     32819
#define ID_LSLOGINSERVERINFO_SERVERBLOCKON 32820
#define ID_LSLOGINSERVERINFO_SERBERBLOCKOFF 32821
#define ID_ENABLE_ALLSERVER             32822
#define ID_DISALBE_ALLSERVER            32823
#define ID_ENABLE_CURRNETSERVER         32824
#define ID_DISABLE_CURRENTSERVER        32825
#define ID_LSLOGINSERVERINFO_32826      32826
#define ID_LOGINSERVERID                32827
#define IDC_BUTTON_REFRESH              32828
#define IDC_STATIC_INFO                 32829
#define IDD_SCROLLABLE                  140
#define IDC_CURSOR1                     141
#define IDC_CURSOR2                     142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
