// stdafx.h : 잘 변경되지 않고 자주 사용하는
// 표준 시스템 포함 파일 및 프로젝트 관련 포함 파일이 
// 들어 있는 포함 파일입니다.

#pragma once

#ifndef _SECURE_ATL
#define _SECURE_ATL 1
#endif

#ifndef VC_EXTRALEAN
#define VC_EXTRALEAN		// Windows 헤더에서 거의 사용되지 않는 내용을 제외시킵니다.
#endif

//// 아래 지정된 플랫폼보다 우선하는 플랫폼을 대상으로 하는 경우 다음 정의를 수정하십시오.
//// 다른 플랫폼에 사용되는 해당 값의 최신 정보는 MSDN을 참조하십시오.
//#ifndef WINVER				// Windows 95 및 Windows NT 4 이후 버전에서만 기능을 사용할 수 있습니다.
//#define WINVER 0x0501		// Windows 98과 Windows 2000 이후 버전에 맞도록 적합한 값으로 변경해 주십시오.
//#endif
//
//#ifndef _WIN32_WINNT		// Windows NT 4 이후 버전에서만 기능을 사용할 수 있습니다.
//#define _WIN32_WINNT 0x0501		// Windows 98과 Windows 2000 이후 버전에 맞도록 적합한 값으로 변경해 주십시오.
//#endif						
//
//#ifndef _WIN32_WINDOWS		// Windows 98 이후 버전에서만 기능을 사용할 수 있습니다.
//#define _WIN32_WINDOWS 0x0501 // Windows Me 이후 버전에 맞도록 적합한 값으로 변경해 주십시오.
//#endif
//
//#ifndef _WIN32_IE			// IE 4.0 이후 버전에서만 기능을 사용할 수 있습니다.
//#define _WIN32_IE 0x0500	// IE 5.0 이후 버전에 맞도록 적합한 값으로 변경해 주십시오.
//#endif

#include <SDKDDKVer.h>

#define _ATL_CSTRING_EXPLICIT_CONSTRUCTORS	// 일부 CString 생성자는 명시적으로 선언됩니다.

// MFC의 공통 부분과 무시 가능한 경고 메시지에 대한 숨기기를 해제합니다.
#define _AFX_ALL_WARNINGS

#include <afxwin.h>         // MFC 핵심 및 표준 구성 요소
#include <afxext.h>         // MFC 익스텐션

#include <afxdisp.h>        // MFC 자동화 클래스입니다.

#ifndef _AFX_NO_OLE_SUPPORT
#include <afxdtctl.h>		// Internet Explorer 4 공용 컨트롤에 대한 MFC 지원
#endif
#ifndef _AFX_NO_AFXCMN_SUPPORT
#include <afxcmn.h>			// Windows 공용 컨트롤에 대한 MFC 지원
#endif // _AFX_NO_AFXCMN_SUPPORT

#include <afxcontrolbars.h>     // MFC의 리본 및 컨트롤 막대 지원

// C RunTime Header Files
#include <stdlib.h>
#include <malloc.h>
#include <mmsystem.h>
#include <memory.h>
#include <tchar.h>
#include <winsock2.h>
// Local Header Files


// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning(disable:4786)

// disable: "conversion from 'double' to 'float', possible loss of data
#   pragma warning(disable:4244)

// disable: "truncation from 'double' to 'float'
#   pragma warning(disable:4305)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#   pragma warning(disable:4251)

// disable: "non dll-interface class used as base for dll-interface class"
// Happens when deriving from Singleton because bug in compiler ignores
// template export
#   pragma warning(disable:4275)

// disable: "C++ Exception Specification ignored"
// This is because MSVC 6 did not implement all the C++ exception 
// specifications in the ANSI C++ draft.
#   pragma warning(disable:4290)

// disable: "no suitable definition provided for explicit template 
// instantiation request" Occurs in VC7 for no justifiable reason on all 
// #includes of Singleton
#   pragma warning(disable:4661)

#   pragma warning(disable:4005)
#	pragma warning(disable:4995)

#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <cstdarg>
#include <cmath>
#include <atldbcli.h>
// STL containers
#include <vector>
#include <map>
#include <string>
#include <set>
#include <list>
#include <deque>

// STL algorithms & functions
#include <algorithm>
#include <functional>
#include <utility>
#include <limits>

// TODO: reference additional headers your program requires here
#define __EX __declspec(dllimport)

#include "IOSocketDLL/IOSocketDLL.h"
#include "../TownPortal/include/TownPortal.h"
#include "ioHashString.h"
#include "../include/common.h"
#include "Define.h"
//#include "common.h"

#ifdef _DEBUG
//#pragma comment(lib, "IOSocketDLL/IOSocketDDLL.lib")
//#pragma comment(lib, "../LSLog/bin/LSLogd.lib" )
//#pragma comment(lib, "../TownPortal/bin/TownPortald.lib")
#pragma comment(lib, "LSLogD.lib" )
#pragma comment(lib, "TownPortalD.lib")
#pragma comment(lib, "iosocketddll.lib")

#pragma comment(lib, "IOSocketDLL.lib")
#pragma comment(lib, "LSLog.lib" )
#pragma comment(lib, "TownPortal.lib")

//#pragma comment(lib, "../LSLog/bin/LSLog.lib" )
//#pragma comment(lib, "../TownPortal/bin/TownPortal.lib")
#else
#pragma comment(lib, "LSLog.lib" )
#pragma comment(lib, "TownPortal.lib")
#pragma comment(lib, "IOSocketDLL.lib")
#endif

#pragma comment(lib, "Winmm.lib")
#include <mmsystem.h>

#include "NetWork/SP2Packet.h"
#include "NetWork/Protocol.h"
#include "NagleRefCountDlg.h"
#define WM_LSLOGINSERVER WM_USER + 800
#define WM_SENDLOGINSERVER WM_USER + 801
#define WM_DISCONNETED WM_USER + 802
typedef struct _SERVERINFO_
{
	std::string ipaddr;
	int port;
	int usercount;
	int sendcount;
	int fullcount;
	std::string servername;
	int serverblockstate;
	int sendserverid;
	int wmid;
	int nstate;


}ServerInfo_;
typedef std::vector<ServerInfo_> VSVRINFO;
 
#define LVSVER "Login Server"
//#endif // _AFX_NO_AFXCMN_SUPPORT

